import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import axios from 'axios';

dotenv.config();

const app = express();
const port = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

app.post('/api/detect', async (req, res) => {
  const { text } = req.body;

  if (!text) {
    return res.status(400).json({ error: 'Text is required' });
  }

  try {
    const apiKey = process.env.GROK_API_KEY;
    if (!apiKey) {
      // Mock response if API key is missing for development
      return res.json({
        percentage: Math.floor(Math.random() * 100),
        reasoning: "API Key not configured. This is a mock response.",
        isMock: true
      });
    }

    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'llama-3.3-70b-versatile',
        messages: [
          {
            role: 'system',
            content: 'You are an AI text detector. Analyze the provided text and estimate the probability that it was generated by an AI. Return your response in JSON format with two fields: "percentage" (a number from 0 to 100) and "reasoning" (a brief explanation).'
          },
          {
            role: 'user',
            content: text
          }
        ],
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        }
      }
    );

    const result = JSON.parse(response.data.choices[0].message.content);
    res.json(result);
  } catch (error: any) {
    console.error('Error calling Grok API:', error.response?.data || error.message);
    res.status(500).json({ error: 'Failed to analyze text' });
  }
});

app.post('/api/analyze-detailed', async (req, res) => {
  const { text } = req.body;

  if (!text) {
    return res.status(400).json({ error: 'Text is required' });
  }

  try {
    const apiKey = process.env.GROK_API_KEY;
    if (!apiKey) {
      // Mock response for development
      const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
      return res.json({
        overallPercentage: Math.floor(Math.random() * 100),
        sentences: sentences.map((s: string) => ({
          text: s.trim(),
          percentage: Math.floor(Math.random() * 100),
          reasoning: "Mock reasoning for individual sentence."
        })),
        isMock: true
      });
    }

    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'llama-3.3-70b-versatile',
        messages: [
          {
            role: 'system',
            content: 'You are an advanced AI text analyzer. Break the input text into its constituent sentences. For each sentence, determine the probability (0-100) that it was AI-generated and provide a short reason. Also provide an overall AI probability score for the entire text. Return your response in JSON format with two fields: "overallPercentage" (number) and "sentences" (an array of objects, each with "text", "percentage", and "reasoning").'
          },
          {
            role: 'user',
            content: text
          }
        ],
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        }
      }
    );

    const result = JSON.parse(response.data.choices[0].message.content);
    res.json(result);
  } catch (error: any) {
    console.error('Error calling Groq API:', error.response?.data || error.message);
    res.status(500).json({ error: 'Failed to analyze text' });
  }
});

app.post('/api/humanize', async (req, res) => {
  const { text } = req.body;

  if (!text) {
    return res.status(400).json({ error: 'Text is required' });
  }

  try {
    const apiKey = process.env.GROK_API_KEY;
    if (!apiKey) {
      return res.json({
        humanizedText: text,
        explanation: "API Key not configured. Returning original text.",
        isMock: true
      });
    }

    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'llama-3.3-70b-versatile',
        messages: [
          {
            role: 'system',
            content: 'You are an expert editor specializing in making AI-generated text sound indistinguishable from human writing. Rewrite the provided text to be more natural, conversational, and varied in structure, while maintaining the original meaning. Return your response in JSON format with two fields: "humanizedText" (the rewritten text) and "explanation" (a brief summary of the changes made).'
          },
          {
            role: 'user',
            content: text
          }
        ],
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        }
      }
    );

    const result = JSON.parse(response.data.choices[0].message.content);
    res.json(result);
  } catch (error: any) {
    console.error('Error calling Groq API:', error.response?.data || error.message);
    res.status(500).json({ error: 'Failed to humanize text' });
  }
});

app.post('/api/humanize-code', async (req, res) => {
  const { code, language } = req.body;

  if (!code) {
    return res.status(400).json({ error: 'Code is required' });
  }

  try {
    const apiKey = process.env.GROK_API_KEY;
    if (!apiKey) {
      return res.json({
        humanizedCode: code,
        explanation: "API Key not configured. Returning original code.",
        isMock: true
      });
    }

    const response = await axios.post(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        model: 'llama-3.3-70b-versatile',
        messages: [
          {
            role: 'system',
            content: `You are a senior software engineer. Your task is to refine AI-generated code to make it look like it was written by a human developer.
            
            Strict Guidelines:
            1. INDENTATION: Use exactly 2 spaces for indentation. Never use 4 spaces or tabs.
            2. BASELINE: Start the first line of code at column 0 (no leading whitespace). Only indent lines that are logically nested (e.g., inside functions, loops, or objects).
            3. COMMENTS: Do not be silent, but do not be verbose. Add a few "high-signal" comments only to explain tough or non-obvious lines of code. Avoid commenting standard boilerplate or self-explanatory logic.
            4. STYLE: Use clean, idiomatic patterns. Avoid overly "perfect" boilerplate.
            5. NAMING: Ensure variable names are descriptive but not overly long or clinical.
            
            Return your response in JSON format with two fields: "humanizedCode" (the updated code) and "explanation" (a brief note on what was cleaned up).`
          },
          {
            role: 'user',
            content: `Language: ${language || 'unknown'}\n\nCode:\n${code}`
          }
        ],
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        }
      }
    );

    const result = JSON.parse(response.data.choices[0].message.content);
    if (result.humanizedCode) {
      result.humanizedCode = result.humanizedCode.trim();
    }
    res.json(result);
  } catch (error: any) {
    console.error('Error calling Groq API:', error.response?.data || error.message);
    res.status(500).json({ error: 'Failed to humanize code' });
  }
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
